# Generated by Django 6.0.6 on 2026-06-29 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст статьи')),
                ('url', models.URLField(unique=True, verbose_name='Ссылка на статью')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата нахождения')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='sources.source', verbose_name='Источник')),
            ],
        ),
    ]
