# Generated by Django 6.0.6 on 2026-06-29 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='created_at',
            new_name='foundAt',
        ),
    ]
