# Generated by Django 6.0.6 on 2026-07-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0002_rename_created_at_article_foundat'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='words',
            field=models.CharField(default='', verbose_name='Ключевые слова'),
        ),
    ]
