# Generated by Django 6.0.6 on 2026-06-29 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True, verbose_name='Ключевое слово')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('url', models.URLField(verbose_name='Ссылка / ID группы')),
                ('source_type', models.CharField(choices=[('site', 'Веб-сайт'), ('vk', 'Группа ВК')], default='site', max_length=10, verbose_name='Тип')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен для парсинга')),
            ],
        ),
    ]
