# Generated by Django 6.0.6 on 2026-07-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True, verbose_name='Ключевое слово')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('url', models.URLField(unique=True, verbose_name='Ссылка / ID группы')),
                ('sourceType', models.CharField(blank=True, choices=[('site', 'сайт'), ('vk', 'ВК'), ('rss', ' RSS')], default='site', max_length=10, verbose_name='Тип')),
                ('isActive', models.BooleanField(default=True, verbose_name='Активен для парсинга')),
                ('patterns', models.TextField(blank=True, default='/', verbose_name='Регулярка')),
                ('rss', models.URLField(blank=True, default='', verbose_name='RSS')),
            ],
        ),
    ]
