# Generated by Django 6.0.6 on 2026-06-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='is_active',
            new_name='isActive',
        ),
        migrations.RemoveField(
            model_name='source',
            name='source_type',
        ),
        migrations.AddField(
            model_name='source',
            name='sourceType',
            field=models.CharField(choices=[('site', 'сайт'), ('vk', 'ВК')], default='site', max_length=10, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.URLField(unique=True, verbose_name='Ссылка / ID группы'),
        ),
    ]
