# Generated by Django 6.0.6 on 2026-07-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_rename_is_active_source_isactive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='patterns',
            field=models.TextField(default='/', verbose_name='Регулярка'),
        ),
    ]
