# Generated by Django 6.0.6 on 2026-07-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0003_source_patterns'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='rss',
            field=models.URLField(default='', verbose_name='RSS'),
        ),
    ]
