# Generated by Django 6.0.6 on 2026-07-01 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0004_source_rss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='rss',
            field=models.URLField(default='', null=True, verbose_name='RSS'),
        ),
    ]
