# Generated by Django 6.0.6 on 2026-07-01 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0005_alter_source_rss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='patterns',
            field=models.TextField(blank=True, default='/', verbose_name='Регулярка'),
        ),
        migrations.AlterField(
            model_name='source',
            name='rss',
            field=models.URLField(blank=True, default='', verbose_name='RSS'),
        ),
        migrations.AlterField(
            model_name='source',
            name='sourceType',
            field=models.CharField(blank=True, choices=[('site', 'сайт'), ('vk', 'ВК')], default='site', max_length=10, verbose_name='Тип'),
        ),
    ]
