# Generated by Django 6.0.6 on 2026-07-02 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0006_alter_source_patterns_alter_source_rss_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='sourceType',
            field=models.CharField(blank=True, choices=[('site', 'сайт'), ('vk', 'ВК'), ('rss', ' RSS')], default='site', max_length=10, verbose_name='Тип'),
        ),
    ]
